require 'yaml'
$settings = YAML.load_file '../settings.yml'

def create_vm(config, node_name)
  config.vm.define node_name do |node|

      node.vm.box = 'azure'
      node.vm.hostname = node_name
      node.ssh.private_key_path = 'C:\Users\jacob\.ssh\id_rsa'

      for i in $ports
          config.vm.network :forwarded_port, guest: i, host: i
      end

      node.vm.provider :azure do |azure, override|
        azure.vm_name = node_name
        azure.resource_group_name = node_name
        azure.virtual_network_name = $virtual_network_name
        azure.nsg_name = $nsg_name
        azure.subnet_name = $subnet_name
        azure.tcp_endpoints = $ports

        azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'
        azure.location = "westeurope"
        azure.vm_size = 'Standard_B1MS'

        azure.tenant_id = $settings['config1']['tenant_id']
        azure.client_id = $settings['config1']['client_id']
        azure.client_secret = $settings['config1']['client_secret']
        azure.subscription_id = $settings['config1']['subscription_id']
      end

      node.vm.provision "shell", path: "install_puppet.sh"

      node.vm.provision "puppet" do |puppet|
        puppet.synced_folder_type = "rsync"
        puppet.working_directory = '/vagrant'
        puppet.environment_path="environments"
        puppet.environment = "env1"
        puppet.options = "--verbose --debug"
      end

    end
end

Vagrant.configure(2) do |config|

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  create_vm(config, 'appserver')
  create_vm(config, "dbserver1112")
  create_vm(config, "web")

  (0..2).each do |i|
      create_vm(config, "tst#{i}")
  end


end
